language: python
sudo: false
python:
- '3.4'
addons:
  postgresql: "9.3"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

env:
  - DJANGO_SETTINGS_MODULE="settings.test_settings" SECRET_KEY=test

branches:
  only:
    - master

script:
  - flake8
  - coverage run --source=url_shortener,shorty --omit='*tests*,*migrations*,*admin*,*wsgi*' manage.py test

after_success:
  - coverage report -m
  - coveralls
